In [1]:
import torch
n = 2

In [2]:
t = torch.randint(0,9,(n, 3, 4))
t

tensor([[[1, 8, 5, 3],
         [2, 1, 0, 5],
         [7, 8, 5, 8]],

        [[8, 6, 4, 1],
         [7, 3, 4, 7],
         [0, 0, 3, 4]]])

In [3]:
m = torch.max(t, dim = -1)
m

torch.return_types.max(
values=tensor([[8, 5, 8],
        [8, 7, 4]]),
indices=tensor([[1, 3, 1],
        [0, 0, 3]]))

In [4]:
m[0].shape

torch.Size([2, 3])

In [5]:
m[0]

tensor([[8, 5, 8],
        [8, 7, 4]])

In [6]:
m[0]**2

tensor([[64, 25, 64],
        [64, 49, 16]])

In [7]:
import torch.nn.functional as F
actions = torch.randint(0,4,(n,))
actions

tensor([3, 3])

In [8]:
t

tensor([[[1, 8, 5, 3],
         [2, 1, 0, 5],
         [7, 8, 5, 8]],

        [[8, 6, 4, 1],
         [7, 3, 4, 7],
         [0, 0, 3, 4]]])

In [9]:
a = actions[:,None].repeat(1,3)
a.shape

torch.Size([2, 3])

In [10]:
hot = F.one_hot(a, 4)
hot

tensor([[[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1]],

        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 0, 0, 1]]])

In [11]:
t_hot = t*hot
t_hot

tensor([[[0, 0, 0, 3],
         [0, 0, 0, 5],
         [0, 0, 0, 8]],

        [[0, 0, 0, 1],
         [0, 0, 0, 7],
         [0, 0, 0, 4]]])

In [12]:
t_fin = torch.sum(t_hot, -1)
t_fin

tensor([[3, 5, 8],
        [1, 7, 4]])

In [13]:
t_fin.shape

torch.Size([2, 3])

In [15]:
import numpy as np
v1 = torch.Tensor(np.array([1, 2, 3]))
v2 = torch.Tensor(np.array([1, 2, 3]))

In [16]:
v1@v2

tensor(14.)

In [17]:
np.append(np.array([1, 2, 3]),1)

array([1, 2, 3, 1])

In [18]:
len(21)

TypeError: object of type 'int' has no len()

In [19]:
1e4/500*1e6

20000000.0

In [20]:
50000/3600

13.88888888888889

In [21]:
142*3

426

In [22]:
142*4

568

In [23]:
v1.repeat(3)

tensor([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [24]:
v1.repeat(1)

tensor([1., 2., 3.])

In [25]:
v1@v2

tensor(14.)

In [26]:
1e6/100/60/60

2.7777777777777777

In [27]:
(v1<0).any()

tensor(False)

In [29]:
len({(1,2),(2,3)})

2

In [31]:
s = 40*40
206/s

0.12875

In [32]:
30/200

0.15

In [3]:
import numpy as np
c1, c2 = np.array([24.5, 19.5]) ,np.array([0., 2.])

In [5]:
np.linalg.norm(c1-c2)

30.108138434649195

In [21]:
m = np.random.randint(0,9,(1,2,3,4))
m

array([[[[0, 3, 6, 2],
         [6, 0, 6, 8],
         [6, 5, 5, 3]],

        [[4, 7, 6, 1],
         [3, 1, 4, 8],
         [8, 7, 4, 6]]]])

In [22]:
m[0,...,1:]#.sum()

array([[[3, 6, 2],
        [0, 6, 8],
        [5, 5, 3]],

       [[7, 6, 1],
        [1, 4, 8],
        [7, 4, 6]]])

In [25]:
m = np.zeros((40, 40,3))

In [30]:
i = np.random.randint(0,9,(40,40))

In [36]:
m[np.where(i>5)].shape

(542, 3)

In [37]:
i

array([[6, 8, 2, ..., 8, 1, 3],
       [1, 3, 0, ..., 8, 4, 5],
       [8, 6, 8, ..., 0, 4, 1],
       ...,
       [4, 3, 5, ..., 8, 7, 3],
       [2, 5, 1, ..., 1, 2, 1],
       [5, 6, 8, ..., 4, 1, 2]])

In [52]:
m[,:].shape

(1, 0, 40, 3)

In [61]:
np.where(np.all())

(array([0]),)

In [58]:
np.where(i>-1)[1].shape

(1600,)

In [76]:
m[np.where(i>5)[0],np.where(i>5)[0],:]=[-1,-1,-1]

In [77]:
np.where(m==-1)

(array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
         5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
        11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
        17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22,
        22, 23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28,
        28, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 33, 33,
        34, 34, 34, 35, 35, 35, 36, 36, 36, 37, 37, 37, 38, 38, 38, 39, 39,
        39]),
 array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
         5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
        11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
        17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22,
        22, 23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28,
        28, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 33, 33

In [80]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [84]:
x[np.where( x > 5 )]


array([6., 7., 8.])

In [82]:

x[np.where( x > 3.0 )]               # Note: result is 1D.

np.where(x < 5, x, -1)               # Note: broadcasting.

array([4., 5., 6., 7., 8.])

In [83]:
np.where(x < 5, x, -1)               # Note: broadcasting.

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])

In [90]:
m = np.arange(27).reshape(3, 3, 3)
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
m[np.where( x > 5 ),:]

array([[[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]])

In [2]:
import numpy as np
from PIL import Image
var = np.zeros((400, 400,3))+200
import matplotlib.pyplot as plt

# plt.imshow(var)
im = Image.fromarray(var.astype(np.uint8))#.convert('RGB')

im.show(var)