In [33]:
import numpy as np

In [34]:
m = np.random.randint(0,2,(2,2,2,3))

In [35]:
m

array([[[[1, 1, 1],
         [1, 0, 0]],

        [[0, 1, 0],
         [0, 0, 0]]],


       [[[0, 1, 1],
         [0, 1, 1]],

        [[0, 0, 1],
         [1, 1, 0]]]])

In [36]:
m[0,...,0]

array([[1, 1],
       [0, 0]])

In [37]:
m.reshape(2, m.shape[1]*m.shape[2], m.shape[3])[0,..., 0]

array([1, 1, 0, 0])

In [38]:
m = np.random.randint(0,9,(2,3,4))
m

array([[[0, 5, 3, 1],
        [8, 5, 5, 1],
        [8, 8, 6, 6]],

       [[5, 3, 2, 4],
        [1, 4, 2, 1],
        [5, 7, 3, 5]]])

In [39]:
m[0].flatten()

array([0, 5, 3, 1, 8, 5, 5, 1, 8, 8, 6, 6])

In [40]:
m[1].flatten()

array([5, 3, 2, 4, 1, 4, 2, 1, 5, 7, 3, 5])

In [42]:
# m.reshape(-1, m.shape[1]*m.shape[2]*m.shape[3])

In [43]:
a = np.random.randint(0,8,5)
a

array([2, 4, 0, 6, 0])

In [44]:
a[:3]

array([2, 4, 0])

In [45]:
1==1==1

True

In [53]:
b = np.random.randint(0,2,(2, 4, 3))
b

array([[[0, 1, 1],
        [0, 1, 1],
        [0, 1, 1],
        [1, 0, 1]],

       [[1, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        [0, 1, 1]]])

In [54]:
c = np.random.randint(0,2,(2, 3, 5))
c

array([[[0, 0, 0, 1, 1],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0]],

       [[1, 1, 1, 0, 0],
        [0, 1, 1, 0, 0],
        [1, 0, 0, 1, 1]]])

In [55]:
b.transpose(0,2,1)

array([[[0, 0, 0, 1],
        [1, 1, 1, 0],
        [1, 1, 1, 1]],

       [[1, 1, 0, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 1]]])

In [56]:
r = np.concatenate((b.transpose(0,2,1),c), axis=2)
r

array([[[0, 0, 0, 1, 0, 0, 0, 1, 1],
        [1, 1, 1, 0, 0, 0, 0, 1, 0],
        [1, 1, 1, 1, 1, 0, 0, 0, 0]],

       [[1, 1, 0, 0, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 1, 1, 0, 0],
        [1, 0, 0, 1, 1, 0, 0, 1, 1]]])

In [61]:
r.shape

(2, 3, 9)

In [70]:
r[:,0,:]

array([[0, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 1, 0, 0]])

In [82]:
rr = np.repeat(r[:,0,:], repeats=3, axis=0).reshape(-1,3,9)
rr

array([[[0, 0, 0, 1, 0, 0, 0, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 1, 1],
        [0, 0, 0, 1, 0, 0, 0, 1, 1]],

       [[1, 1, 0, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 0, 1, 1, 1, 0, 0]]])

In [83]:
r = np.concatenate((r,rr), axis=2)

In [84]:
r = r.transpose(0,2,1)
r

array([[[0, 1, 1],
        [0, 1, 1],
        [0, 1, 1],
        [1, 0, 1],
        [0, 0, 1],
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]]])

In [168]:
# np.concatenate(b[0, :, 0], c[0, 0, :])
c[0, 0, :]
b[0, :, 0]
np.append(b[0, :, 0], c[0, 0, :])
# np.column_stack()


array([0, 1, 0, 0, 1, 0, 0, 1])

In [169]:
output = np.zeros((2, 4, 4, 3))

In [31]:
# output[:2,:4,:4,:]=bt

In [45]:
state = np.load('output.npy')

In [55]:
pacman1_loc = np.where(state[..., 0] > 0)
pacman1_loc

(array([24, 25]), array([20, 20]))

In [53]:
pacman1_loc = zip(*np.where(state[..., 0] > 0))
list(pacman1_loc)

[(24, 20), (25, 20)]

In [56]:
ghost1_loc = np.where(state[..., 1] > 0)
ghost1_loc

(array([12, 12, 13, 13]), array([19, 20, 19, 20]))

In [57]:
def centroid(x, y):
    if x.shape[0]==0 or y.shape[0]==0: return np.array([])
    assert x.shape[0] == y.shape[0]
    mid = lambda x: x.min()+(x.max() - x.min())//2
    return np.array([mid(x), mid(y)])

In [58]:
centroid(*pacman1_loc)

array([24, 20])

In [60]:
centroid(*ghost1_loc)

array([12, 19])

In [62]:
3>=2>2

False

In [78]:
a

array([4, 0, 1, 5, 7])

In [81]:
a[np.newaxis, :].shape

(1, 5)

In [80]:
a

array([4, 0, 1, 5, 7])

In [1]:
import torch

In [2]:
torch.rand((2,3))

tensor([[0.3822, 0.1549, 0.6436],
        [0.2270, 0.3647, 0.8964]])

In [88]:
b = torch.randint(0,9,(2,4,3))
b

tensor([[[5, 7, 7],
         [1, 4, 7],
         [3, 2, 6],
         [2, 8, 5]],

        [[6, 4, 3],
         [5, 0, 8],
         [0, 3, 7],
         [6, 3, 1]]])

In [89]:
b[:,:,[0,2]]#.flatten()

tensor([[[5, 7],
         [1, 7],
         [3, 6],
         [2, 5]],

        [[6, 3],
         [5, 8],
         [0, 7],
         [6, 1]]])

In [106]:
b[:,:,[0,2]].shape

torch.Size([2, 4, 2])

In [125]:
b.flatten(1,2)

tensor([[5, 7, 7, 1, 4, 7, 3, 2, 6, 2, 8, 5],
        [6, 4, 3, 5, 0, 8, 0, 3, 7, 6, 3, 1]])

In [147]:
b[:,:,[0,2]].permute(2,1,0).flatten(start_dim=1)#.flatten(1)

tensor([[5, 6, 1, 5, 3, 0, 2, 6],
        [7, 3, 7, 8, 6, 7, 5, 1]])

In [144]:
b[:,:,[0,2]].transpose(0,2).permute(2,1,0).flatten(1)

tensor([[5, 7, 1, 7, 3, 6, 2, 5],
        [6, 3, 5, 8, 0, 7, 6, 1]])

In [92]:
f = torch.nn.Flatten()

In [146]:
# THIS WORKS!!!!!!!!!!!!!!
f(b[:,:,[0,2]].permute(0,2,1))

tensor([[5, 1, 3, 2, 7, 7, 6, 5],
        [6, 5, 0, 6, 3, 8, 7, 1]])

In [94]:
b[:,:,[0,2]].flatten(end_dim=2)

tensor([5, 7, 1, 7, 3, 6, 2, 5, 6, 3, 5, 8, 0, 7, 6, 1])

In [95]:
b[:,:,[0,2]].permute(2,0,1).flatten(start_dim=1)

tensor([[5, 1, 3, 2, 6, 5, 0, 6],
        [7, 7, 6, 5, 3, 8, 7, 1]])

In [96]:
b[:,:,[0,2]].permute(2,0,1).flatten(start_dim=1).shape

torch.Size([2, 8])

In [30]:
255//255

1